version: "3"
services:
  laundry_api:
    container_name: laundry_api
    build:
      context: .
      dockerfile: Dockerfile_api_uwsgi
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5000:5000
    links:
     - elasticsearch
     - redis
    logging:
      driver: "json-file"
    #command: ["./wait-for-it.sh", "elasticsearch:9200", "--", "uwsgi",  "--http", "0.0.0.0:5000", "-b", "32768", "--wsgi-file", "merge_machine/api.py", "--callable", "app", "--processes", "4", "--threads","2"] 
  laundry_worker:
    container_name: laundry_worker
    build:
      context: .
      dockerfile: Dockerfile_rqworker
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
     - elasticsearch
     - redis
    logging:
      driver: "json-file"
    command: ["./wait-for-it.sh", "elasticsearch:9200", "--", "python3", "merge_machine/worker.py"]
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes

