version: "3"
services:
  laundry:
    container_name: laundry
    build:
      context: .
    # command: ["./wait-for-it.sh", "elasticsearch:9200", "--", "python3", "merge_machine/worker.py"]
    # command: ["./wait-for-it.sh", "elasticsearch:9200", "--", "curl", "-u elastic http://127.0.0.1:9200/_cat/health"]
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5000:5000
    links:
     - elasticsearch
     - redis
    logging:
      driver: "json-file"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes

